// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLuCXRp107z4j5IrMPpJvp5Zb5xIgd6og',
    appId: '1:38802259546:android:8d4410c3d9fa47da5e6263',
    messagingSenderId: '38802259546',
    projectId: 'backend-klinik',
    storageBucket: 'backend-klinik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcRPON4yL9jnbXe_O2fUGJJ0ZCDZglz80',
    appId: '1:38802259546:ios:580ec4c0bc003c005e6263',
    messagingSenderId: '38802259546',
    projectId: 'backend-klinik',
    storageBucket: 'backend-klinik.firebasestorage.app',
    iosBundleId: 'com.example.testFront',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLuCXRp107z4j5IrMPpJvp5Zb5xIgd6og',
    appId: '1:38802259546:web:8d4410c3d9fa47da5e6263',
    messagingSenderId: '38802259546',
    projectId: 'backend-klinik',
    authDomain: 'backend-klinik.firebaseapp.com',
    storageBucket: 'backend-klinik.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

}